name: satyatest1
on: [push,workflow_dispatch]
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Install dependencies
          run: npm ci
        - name: npm lint
          run: npm run lint
        - name: npm test
          run: npm run test
        - name: npm build
          run: npm run build
        - name: npm start
          run: npm start 
