name: satyatest2
on: 
    issues:
        types: [opened, edited, deleted, closed, reopened]  
jobs:
 test3:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: echo context
          run: echo "{{ toJson(github)}}"